### ISSUE TITLE
Project not found

### ISSUE THREAD

**Issue by davidoort** [krabhishek/flutterflow-vscode-extension#3]
Hi, after configuring my project name, API key and path I am running the sync command and get the following error:
```
pub global run flutterflow_cli export-code --project Giftit --dest /Users/dalonso/git/giftit/giftit_ff_test/78417995 --include-assets --token <API key pasted from FF> Error: Project not found.
```
The project name was pasted directly from here:
![image](https://user-images.githubusercontent.com/21220927/215081466-2a98d5ab-acd1-4b01-b4c1-72728a89929a.png)

Please let me know how I can fix this :)

**Comment by decoded-io** [comment]
Try copying the project ID from the URL. https://app.flutterflow.io/project/myproject-xxxxxx 
It is usually your project name with a dash and 6 random characters. E.g. myproject-xxxxxx

**Comment by davidoort** [comment]
Fixed, thanks!
