### ISSUE TITLE
Downloading to <project> subdirectory

### ISSUE THREAD

**Issue by davidoort** [krabhishek/flutterflow-vscode-extension#6]
Hi @krabhishek , every time I download code, the extension creates a folder named <project> inside my flutter project containing the entire flutter project, meaning that if I have a session running on the current codebase, that code will not be updated. This didn't happen in the previous version with the working directory parameter.

**Comment by davidoort** [comment]
If anyone is having the same issue, you can revert to version 0.0.3

**Comment by krabhishek** [comment]
@davidoort this is actually the new intended behavior. Considering that many users would have multiple projects, the plugin now uses a base directory where it downloads each project in their own folders. Moreover, it also gives you an option to automatically initialize git locally and also automatically open the folder in a vscode window. Please check out the latest release for the same.

**Comment by davidoort** [comment]
Yep I read that, but the behavior I'm getting is:
Have a vscode workspace open in <path/to/base/folder>. After running the extension once, inside this workspace I have a folder <project_name>. If I run the plugin again, without changing anything, the project gets downloaded to the path <path/to/base/folder/project_name/project_name>. I don't think this is the intended behavior right?

**Comment by israpasos** [comment]
I'm having the exact same problem.

**Comment by israpasos** [comment]
Perhaps forcing the structure into a monorepo should be an option not a requirement. If the intention is to have it behave as a monorepo, perhaps it would be better to research a way to integrate with turborepo or nx.

**Comment by krabhishek** [comment]
@davidoort @TzuTech that is not the intended behavior. Can you please confirm that you are on v0.0.6 of the plugin and you can recreate this?

**Comment by krabhishek** [comment]
Ideally, the design that I have in mind is that you have one basepath (a folder) where all your flutterflow projects live in their own respective folders. It is not a monorepo as the basepath itself is not part of your git structure but more like FLUTTERFLOW_HOME where all projects live in their own respective folders.
