### ISSUE TITLE
A second project folder is created in the first folder 

### ISSUE THREAD

**Issue by mrnicon** [krabhishek/flutterflow-vscode-extension#7]
The first time I download the project code the projekt folder with the project name is created (all code included), the next time I run download projekt code it create another subfolder with the same name and put the code in this dir also . 
so I now have /dev/flutterflow/my_app/my_app
And the latest code is always in the deepest dir.. 
/dev/flutterflow/ is set as the Base Directory. 
Compiling the code in the deepest dir is working fine and gives me the latest code - but it might not be the perfect solution :-) 

BTW Nice work..

**Comment by krabhishek** [comment]
Thanks for reporting this. This indeed is a bug. I will try and fix it.

**Comment by krabhishek** [comment]
@mrnicon - I have fixed the code. Could you please test it and let me know if it works for you?

**Comment by krabhishek** [comment]
You need to update the plugin to v0.0.7

**Comment by mrnicon** [comment]
Works like a charm.
Thank you!

Just a thought, is it possible to have the settings per catalog, I
often develop in different projects at the same time, then its a little
inconvenient to have to change project id all the time.


Best regards
Arnstein Njåstad
